name: CustomSkulls
main: com.timvisee.customskulls.CustomSkulls
version: 0.3
author: timvisee
authors: [PatPeter]
website: http://dev.bukkit.org/server-mods/custom-skulls/
depend: [Vault]
commands:
    customskulls:
      description: Custom Skulls command
      usage: /customskulls
    customskull:
      description: Custom Skulls command
      usage: /customskull
    skulls:
      description: Custom Skulls command
      usage: /skulls